---
version: '3.8'
services:
  prd-mosquitto-app:
    image: docker-registry.theautomation.nl/coen/prd-mosquitto-app:latest
    container_name: prd-mosquitto-app
    restart: always
    env_file: prd-mosquitto-app.env
    volumes:
      - ./config:/mosquitto/config
      - ./log:/mosquitto/log
      - ./data:/mosquitto/data
    ports:
      - 1883:1883 #exposed for home assistant
    networks:
      - mosquitto

networks:
  mosquitto:
    name: mosquitto
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
